### ISSUE TITLE
Failed pip/pipsi installation

### ISSUE THREAD

**Issue by shepilov-vladislav** [funkyfuture/compose-dump#1]
root@server:~# pip install compose-dump
Collecting compose-dump
  Using cached compose-dump-0.1b2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-JzMowp/compose-dump/setup.py", line 8, in <module>
        install_requires = [x for x in open('requirements.txt').readlines() if x and not x.startswith('#')]
    IOError: [Errno 2] No such file or directory: 'requirements.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-JzMowp/compose-dump/

**Comment by funkyfuture** [comment]
thanks for reporting. there was the *release*  item left on my short-term todo-list. done that now.
